substitutions:
  devicename: air-quality
  friendlydevicename: Air Quality

esphome:
    name: $devicename
    comment: $friendlydevicename ESP8266 controller
    on_boot:
      priority: 600
      then:
        - deep_sleep.prevent: deep_sleep_1

esp8266:
  board: d1_mini

# Enable logging
logger:
    baud_rate: 0

ota:
  password: blabla #!secret ota_pwd

wifi:
  ssid: blabla #!secret wifi_ssid
  password: blablablablablabla #!secret wifi_pwd
  fast_connect: true
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $friendlydevicename Fallback Hotspot
    password: blablablablablabla #!secret fallback_pwd

captive_portal:

mqtt:
  broker: 10.10.10.10 #!secret mqtt_ip
  port: 1 #!secret mqtt_port
  username: blabla #!secret mqtt_user
  password: blabla #!secret mqtt_pwd
  birth_message:
  will_message:
  discovery: true

deep_sleep:
  run_duration: 10s
  sleep_duration: 15min
  id: deep_sleep_1
  
uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
      on_value:
        then:
          - if:
              condition:
                mqtt.connected:
              then:
                - deep_sleep.allow: deep_sleep_1