esphome:
    name: water-meter
    comment: Water Meter ESP8266 controller

esp8266:
  board: d1_mini

# Enable logging
logger:

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water Meter Fallback Hotspot"
    password: !secret fallback_pwd

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: Water Meter Input
    filters:
      - delayed_on_off: 0.2s
    
sensor:
  - platform: uptime
    name: Device Uptime
    unit_of_measurement: "s"
    update_interval: 1h

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: true